language: node_js
node_js:
  - '8'

addons:
  firefox: "latest"

env:
  - MOZ_HEADLESS=1

script:
  - npm test

install:
  - npm install
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script:
  - npm run lint
